### ISSUE TITLE
RxDB : проблема с созданием папки для базы данных

### ISSUE THREAD

**Issue by senya-g** [bmstu-iu9/utp2018-1-chat#35]
Error output:
```
UnhandledPromiseRejectionWarning: OpenError: IO error: /utp2018-1-chat/application/data/gist-rxdb-0-users/LOCK: No such file or directory
    at /utp2018-1-chat/node_modules/pouchdb-adapter-leveldb-core/node_modules/levelup/lib/levelup.js:91:23
    at /utp2018-1-chat/node_modules/abstract-leveldown/abstract-leveldown.js:41:14
    at /utp2018-1-chat/node_modules/deferred-leveldown/deferred-leveldown.js:20:21
    at /utp2018-1-chat/node_modules/pouchdb-adapter-leveldb/node_modules/abstract-leveldown/abstract-leveldown.js:41:14
```

Если в директории приложения нет папки `data`, то БД не создается, т.к. не может ее создать.
На Windows такой проблемы нет.

**Comment by senya-g** [comment]
Временное решение -- создать пустую директорию 'data',

**Comment by senya-g** [comment]
Решено #38
