### ISSUE TITLE
БД :  this._parentSubscription.unsubscribe is not a function

### ISSUE THREAD

**Issue by senya-g** [bmstu-iu9/utp2018-1-chat#39]
Ошибка при обращении к базе данных (не критическая):
```bash
UnhandledPromiseRejectionWarning: TypeError: this._parentSubscription.unsubscribe is not a function
    at Subscriber._unsubscribeParentSubscription (/home/dev/workspace/education/utp2018-1-chat/node_modules/rxjs/internal/Subscriber.js:108:38)
    at Subscriber.complete (/home/dev/workspace/education/utp2018-1-chat/node_modules/rxjs/internal/Subscriber.js:82:18)
    at DataMigrator._callee$ (/home/dev/workspace/education/utp2018-1-chat/node_modules/rxdb/dist/lib/data-migrator.js:204:46)
    at tryCatch (/home/dev/workspace/education/utp2018-1-chat/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/home/dev/workspace/education/utp2018-1-chat/node_modules/regenerator-runtime/runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (/home/dev/workspace/education/utp2018-1-chat/node_modules/regenerator-runtime/runtime.js:114:21)
    at step (/home/dev/workspace/education/utp2018-1-chat/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /home/dev/workspace/education/utp2018-1-chat/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:24147) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:24147) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:24147) UnhandledPromiseRejectionWarning: TypeError: this._parentSubscription.unsubscribe is not a function
    at Subscriber._unsubscribeParentSubscription (/home/dev/workspace/education/utp2018-1-chat/node_modules/rxjs/internal/Subscriber.js:108:38)
    at Subscriber.complete (/home/dev/workspace/education/utp2018-1-chat/node_modules/rxjs/internal/Subscriber.js:82:18)
    at DataMigrator._callee$ (/home/dev/workspace/education/utp2018-1-chat/node_modules/rxdb/dist/lib/data-migrator.js:204:46)
    at tryCatch (/home/dev/workspace/education/utp2018-1-chat/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/home/dev/workspace/education/utp2018-1-chat/node_modules/regenerator-runtime/runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (/home/dev/workspace/education/utp2018-1-chat/node_modules/regenerator-runtime/runtime.js:114:21)
    at step (/home/dev/workspace/education/utp2018-1-chat/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /home/dev/workspace/education/utp2018-1-chat/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:24147) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:24147) UnhandledPromiseRejectionWarning: TypeError: this._parentSubscription.unsubscribe is not a function
    at Subscriber._unsubscribeParentSubscription (/home/dev/workspace/education/utp2018-1-chat/node_modules/rxjs/internal/Subscriber.js:108:38)
    at Subscriber.complete (/home/dev/workspace/education/utp2018-1-chat/node_modules/rxjs/internal/Subscriber.js:82:18)
    at DataMigrator._callee$ (/home/dev/workspace/education/utp2018-1-chat/node_modules/rxdb/dist/lib/data-migrator.js:204:46)
    at tryCatch (/home/dev/workspace/education/utp2018-1-chat/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/home/dev/workspace/education/utp2018-1-chat/node_modules/regenerator-runtime/runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (/home/dev/workspace/education/utp2018-1-chat/node_modules/regenerator-runtime/runtime.js:114:21)
    at step (/home/dev/workspace/education/utp2018-1-chat/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /home/dev/workspace/education/utp2018-1-chat/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:24147) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
```

**Comment by senya-g** [comment]
Ошибка оказалась "локальной".
Закрыто.
